import 'package:supabase_flutter/supabase_flutter.dart';
import '../models/transaction_model.dart';
import 'supabase_service.dart';

class TransactionRepository {
  final SupabaseClient _supabase = SupabaseService.client;

  Stream<List<TransactionModel>> getTransactionsStream(String userId) {
    return _supabase
        .from(SupabaseService.transactionsTable)
        .stream(primaryKey: ['id'])
        .eq('user_id', userId)
        .order('date', ascending: false)
        .map(
          (data) => data
          .map((json) => TransactionModel.fromJson(json))
          .toList(),
    );
  }

  Future<TransactionModel> addTransaction(
      TransactionModel transaction,
      ) async {
    if (transaction.userId.trim().isEmpty ||
        transaction.categoryId.trim().isEmpty) {
      throw Exception('Invalid transaction data');
    }

    final response = await _supabase
        .from(SupabaseService.transactionsTable)
        .insert({
      // ❌ NEVER send id (UUID auto-generated by DB)
      'user_id': transaction.userId.trim(),
      'category_id': transaction.categoryId.trim(),
      'amount': transaction.amount,
      'type': transaction.type,
      'note': transaction.note,
      'date': transaction.date.toIso8601String().split('T')[0],
      'created_at': transaction.createdAt.toIso8601String(),
    })
        .select()
        .single();

    return TransactionModel.fromJson(response);
  }

  Future<TransactionModel> updateTransaction(
      TransactionModel transaction,
      ) async {
    if (transaction.id.trim().isEmpty) {
      throw Exception('Invalid transaction id');
    }

    final response = await _supabase
        .from(SupabaseService.transactionsTable)
        .update({
      'user_id': transaction.userId.trim(),
      'category_id': transaction.categoryId.trim(),
      'amount': transaction.amount,
      'type': transaction.type,
      'note': transaction.note,
      'date': transaction.date.toIso8601String().split('T')[0],
    })
        .eq('id', transaction.id)
        .select()
        .single();

    return TransactionModel.fromJson(response);
  }

  Future<void> deleteTransaction(String id) async {
    if (id.trim().isEmpty) {
      throw Exception('Invalid transaction id');
    }

    await _supabase
        .from(SupabaseService.transactionsTable)
        .delete()
        .eq('id', id);
  }
}